# Generated by Django 5.1.4 on 2024-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paragraph", models.TextField()),
                (
                    "winner_name",
                    models.CharField(max_length=255, verbose_name="Winner's Name"),
                ),
                (
                    "social_media_url",
                    models.CharField(max_length=255, verbose_name="Winner's Name"),
                ),
                ("image_1", models.CharField(max_length=255, verbose_name="Image 1")),
                ("image_2", models.CharField(max_length=255, verbose_name="Image 2")),
                ("image_3", models.CharField(max_length=255, verbose_name="Image 3")),
                (
                    "alt_text_1",
                    models.CharField(max_length=255, verbose_name="Alt Text 1"),
                ),
                (
                    "alt_text_2",
                    models.CharField(max_length=255, verbose_name="Alt Text 2"),
                ),
                (
                    "alt_text_3",
                    models.CharField(max_length=255, verbose_name="Alt Text 3"),
                ),
                ("headline", models.CharField(max_length=255, verbose_name="Headline")),
            ],
        ),
    ]
