# Generated by Django 5.1.4 on 2024-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotlight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winner",
            name="social_media_url",
            field=models.CharField(max_length=255, verbose_name="Social Media Link"),
        ),
    ]
