# Generated by Django 5.1.2 on 2025-01-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Color Name')),
                ('clicked', models.IntegerField()),
                ('chosen', models.IntegerField()),
                ('percent', models.FloatField(blank=True)),
            ],
        ),
    ]
