# Generated by Django 5.1.2 on 2025-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='chosen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='color',
            name='clicked',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='color',
            name='percent',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
